color: null
fieldLayouts:
  4a638b79-5b4b-4326-86e5-7b042cf3c3be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-01T20:43:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e8f33bef-afc6-4060-8e1d-45080c48b4de
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-02T09:42:29+00:00'
            elementCondition: null
            fieldUid: 2731f8ce-9d28-4719-a7b5-7648654abd3a # Social Media URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48bade21-011d-4bb3-9834-8aac9af18e49
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-02T09:48:57+00:00'
            elementCondition: null
            fieldUid: 256d6abe-15f3-4cdc-b8f6-c2e3b54bd7d7 # Button Font Family
            handle: iconHandle
            includeInCards: false
            instructions: null
            label: 'Icon Handle'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62553863-aa82-49a7-9611-e51c71e2d228
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03383215-2fe6-4562-9841-d4944001b240
        userCondition: null
handle: socialMediaChannel
hasTitleField: true
icon: hashtag
name: 'Social Media Channel'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
