columnSuffix: null
handle: logoSvg
instructions: null
name: 'Logo SVG'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  initialRows: 12
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
