dateModified: 1730637538
email:
  fromEmail: carl@avidanodigital.com
  fromName: 'Natura11y Craft'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  globalAssets:
    hasUrls: true
    name: 'Global Assets'
    settings:
      path: '@webroot/uploads/global-assets'
    type: craft\fs\Local
    url: '@web/uploads/global-asset'
meta:
  __names__:
    1c5172e7-9eed-4ee0-9383-38ac0831d00d: 'Theme Colors' # Theme Colors
    7cb174b6-5c07-4b57-89a0-7c1f6407cc5c: Typography # Typography
    8da06d95-e6be-4ffe-96aa-97abe9318b70: 'Color Scheme' # Color Scheme
    9e3bd4d0-053b-4539-94d8-f4e755ca755e: 'Social Media' # Social Media
    80e0cc69-6149-4078-a30d-25b9c15772c0: 'Public Schema' # Public Schema
    97cf5dd0-3430-47f6-8f8c-757a736dfea6: 'Logo SVG' # Logo SVG
    250a3b60-09d8-4e5b-82d2-904a41aca078: 'CSS Code' # CSS Code
    256d6abe-15f3-4cdc-b8f6-c2e3b54bd7d7: 'Button Font Family' # Button Font Family
    770cfc06-059b-41d8-9083-bf3215a0ed68: 'HTML Code' # HTML Code
    2731f8ce-9d28-4719-a7b5-7648654abd3a: 'Social Media URL' # Social Media URL
    10665a14-f1e0-402e-93bd-030cadf2e7a9: 'Social Media Channel' # Social Media Channel
    587855bf-d3e2-4b8d-bb33-b8a243f0c26b: 'Social Media Channels' # Social Media Channels
    840456cc-6313-485e-a607-e2debcca5328: 'Font Embed Code' # Font Embed Code
    52015185-6c75-42e2-b849-16af964e6f4b: 'Theme Color' # Theme Color
    a4638ec6-b512-436e-9c4f-13ab670a8309: 'Logo Image' # Logo Image
    d564a43f-3e8f-49ed-a599-df6640d837c5: 'Natura11y Craft' # Natura11y Craft
    e9751f72-d746-49b3-ad2f-a5b32abb0cb5: 'Global Assets' # Global Assets
    eb158f32-2e82-4a74-ac4d-7a2c751d8160: 'Brand Logo' # Brand Logo
    f1ade01c-5513-48c6-ba5c-61d671ad8444: 'Natura11y Craft' # Natura11y Craft
plugins:
  codefield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Natura11y Craft'
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
