fieldLayouts:
  9fb12c72-ba60-4fe1-9301-5a0c8dd5117f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-01T20:04:55+00:00'
            elementCondition: null
            fieldUid: a4638ec6-b512-436e-9c4f-13ab670a8309 # Logo Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb681701-5ebb-4d22-b076-8a660e3eb2c3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-02T20:22:39+00:00'
            elementCondition: null
            fieldUid: 770cfc06-059b-41d8-9083-bf3215a0ed68 # HTML Code
            handle: logoSvg
            includeInCards: false
            instructions: null
            label: LogoSVG
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df6d82e2-1ed7-4bb1-9787-602206d80149
            userCondition: null
            warning: null
            width: 100
        name: 'Brand Logo'
        uid: 232a986d-5032-40d4-9d31-b0163414d60e
        userCondition: null
handle: brandLogo
name: 'Brand Logo'
sortOrder: 1
