fieldLayouts:
  9fb12c72-ba60-4fe1-9301-5a0c8dd5117f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-01T20:04:55+00:00'
            elementCondition: null
            fieldUid: a4638ec6-b512-436e-9c4f-13ab670a8309 # Logo Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb681701-5ebb-4d22-b076-8a660e3eb2c3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-01T20:04:55+00:00'
            elementCondition: null
            fieldUid: 97cf5dd0-3430-47f6-8f8c-757a736dfea6 # Logo SVG
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71fc6d01-4c2e-4a02-813f-95d29181b4db
            userCondition: null
            warning: null
            width: 100
        name: Brand
        uid: 232a986d-5032-40d4-9d31-b0163414d60e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-01T20:46:25+00:00'
            elementCondition: null
            fieldUid: 587855bf-d3e2-4b8d-bb33-b8a243f0c26b # Social Media Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0893a34a-feab-49a5-b23f-0caab2a975fa
            userCondition: null
            warning: null
            width: 100
        name: 'Social Media'
        uid: 1b650a6d-3a2e-4379-ac30-d5e14ead4fbf
        userCondition: null
handle: siteSettings
name: 'Site Settings'
sortOrder: 1
