fieldLayouts:
  2ac33e3d-6e64-4d46-9982-270241ecf993:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-02T10:13:55+00:00'
            elementCondition: null
            fieldUid: 52015185-6c75-42e2-b849-16af964e6f4b # Theme Color
            handle: primaryColor
            includeInCards: false
            instructions: 'The primary color'
            label: 'Primary Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2bb8958-5b81-4e86-8ce2-f6cd8d4cf2dc
            userCondition: null
            warning: null
            width: 100
        name: Primary
        uid: 14c12e7e-f15f-44e2-ac63-be10e6e574d5
        userCondition: null
handle: themeColors
name: 'Theme Colors'
sortOrder: 2
